language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - make yapf
  - make lint
  - coverage run tests.py
after_success:
  - pip install codecov
  - codecov
